# Config file for [`cargo-release`](https://github.com/crate-ci/cargo-release)
# See: https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

allow-branch = ["main"]
shared-version = true  # all crates share one version, one tag
pre-release-commit-message = "chore: release {{version}}"
tag-prefix = "celo/v"  # create git tags like celo/v1.0.0
